# Generated by Django 4.1.5 on 2023-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
