# Generated by Django 4.1.5 on 2023-01-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopparser', '0002_alter_shop_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketstate',
            old_name='Autoreg_count',
            new_name='Autoreg_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='Autoreg_cost',
            new_name='Autoreg_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='BM_count',
            new_name='BM_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='BM_cost',
            new_name='BM_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='FP_count',
            new_name='FP_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='FP_cost',
            new_name='FP_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='Farm_count',
            new_name='Farm_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='Farm_cost',
            new_name='Farm_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='PZRDFP_count',
            new_name='PZRDFP_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='PZRDFP_cost',
            new_name='PZRDFP_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='Undef_count',
            new_name='Undef_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='Undef_cost',
            new_name='Undef_sumSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='ZRD_count',
            new_name='ZRD_countSold',
        ),
        migrations.RenameField(
            model_name='marketstate',
            old_name='ZRD_cost',
            new_name='ZRD_sumSold',
        ),
        migrations.CreateModel(
            name='DayStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_update', models.TimeField(auto_now_add=True)),
                ('BM_countSold', models.BigIntegerField()),
                ('BM_sumSold', models.BigIntegerField()),
                ('ZRD_countSold', models.BigIntegerField()),
                ('ZRD_sumSold', models.BigIntegerField()),
                ('Farm_countSold', models.BigIntegerField()),
                ('Farm_sumSold', models.BigIntegerField()),
                ('Autoreg_countSold', models.BigIntegerField()),
                ('Autoreg_sumSold', models.BigIntegerField()),
                ('FP_countSold', models.BigIntegerField()),
                ('FP_sumSold', models.BigIntegerField()),
                ('PZRDFP_countSold', models.BigIntegerField()),
                ('PZRDFP_sumSold', models.BigIntegerField()),
                ('Undef_countSold', models.BigIntegerField()),
                ('Undef_sumSold', models.BigIntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopparser.shop')),
            ],
        ),
    ]
