# Generated by Django 4.1.5 on 2023-02-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopparser', '0004_rename_autoreg_sumsold_daystat_autoreg_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystat',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketstate',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopstate',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
